package: adminer
version: '2.1.0'
vendor: '4.17.1 adminer'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/adminer

page:
    title: Adminer
    perm: admin
    live_mode: false
    hasLayout: false
    icon: rex-icon fa-database
    linkAttr: { target: _blank }

requires:
    php: '>=5.5'
    redaxo: '^5.0'
