package: adminer
version: '2.0.1'
vendor: '4.8.3 adminerevo'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/adminer

page:
    title: AdminerEvo
    perm: admin
    live_mode: false
    hasLayout: false
    icon: rex-icon fa-database
    linkAttr: { target: _blank }

requires:
    php: '>=5.5'
    redaxo: '^5.0'
