package: adminer
version: '1.9.0'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/adminer

page:
    title: Adminer
    perm: admin
    hasLayout: false
    icon: rex-icon fa-database
    linkAttr: { target: _blank }

requires:
    php: '>=5.5'
    redaxo: '^5.0'
